test

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -17,14 +17,19 @@ jobs:
         uses: actions/checkout@v5
       - uses: actions/setup-node@v5
         with:
-          node-version: '24'
+          node-version: "24"
       - run: npm ci
       - run: npx tsc -b
       - name: Test server startup
-      # TODO: continue here
         run: |
-          npm run prod &
+          npm run prod & SERVER_PID=$!
           sleep 5
+          if ! ps -p $SERVER_PID > /dev/null; then
+            echo "Server process failed to start."
+            exit 1
+          fi
+          echo "Server started successfully. Killing process."
+          kill $SERVER_PID
           exit 0
         env:
           HTTPS: false
