test

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -25,13 +25,11 @@ jobs:
           NODE_PID=$!
           echo $NODE_PID
           sleep 5
-          if [ ! -z $NODE_PID ]; then
-              echo "sucess"
-              exit 0;
-          else
-              echo "failed"
-              exit 1;
+          if [ -z $NODE_PID ]; then
+            echo "Express failed to start."
+            exit 1;
           fi;
+          exit 0;
         env:
           HTTPS: false
 
