test

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -22,15 +22,16 @@ jobs:
       - run: npx tsc -b
       - run: |
           npm run prod &
+          NODE_PID=$!
+          echo $NODE_PID
           sleep 5
-          NODE_PID=$(pgrep -f "server.ts")
-          if [ -z "$NODE_PID" ]; then
-            echo "Express failed on startup."
-            exit 1
-          fi
-          echo "Express started successfully. Killing process."
-          kill $NODE_PID
-          exit 0
+          if [ ! -z $NODE_PID ]; then
+              echo "sucess"
+              exit 0;
+          else
+              echo "failed"
+              exit 1;
+          fi;
         env:
           HTTPS: false
 
